### PR TITLE
User contact

### PR DESCRIPTION
**Pull request by femithz**

### CODE REVIEW

**Comment by raphaelakpan** [comment]
When you open a Pull Request, you need to add description on what was added, and steps to test it and what to expect, basically everything that can help someone understand what was implemented. Here's an example.

image

Please do so on both open PRs.

**Comment by femithz** [comment]
- [ ]      User Contact 

- An endpoint to create a contact for a user is created.
    And is named ----- contacts
- Every of the contact created is associated with the logged-in user.
- A test endpoint is created to test for both the success and error if any occurs.

**Comment by raphaelakpan** [comment]
You can merge the PR if it works as expected. I'll create the next stories @femithz

**Comment by femithz** [comment]
okay, sir.

**Pull request merged**
